version: '3'

services:
    
  mongodb:
    image: mongo
    container_name: mongodb   
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    hostname: mongodb-server
    volumes:
      - ./mongo_user.js:/docker-entrypoint-initdb.d/mongo_user.js:ro
      - ./mongo-data:/data/db     
  
  #mongo-express:
  #  image: mongo-express
  #  container_name: mongo-express    
  #  ports:
  #    - "8080:8081"
  #  restart: unless-stopped       
  #  environment:
  #    - ME_CONFIG_MONGODB_ADMINUSERNAME=iuvity
  #    - ME_CONFIG_MONGODB_ADMINPASSWORD=iuvity
  #    - ME_CONFIG_MONGODB_SERVER=mongodb

  backend:
    build:
      context: ./backend-iuvity
      target: dev
    container_name: backend-iuvity  
    volumes:
      - .:/src
    depends_on:
      - mongodb
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: backend-iuvity:*